---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r message = F, warning = F}
library(here)
library(tidyverse)
```

```{r message = F, warning = F}
seabirds_full_clean <- read_csv(here("clean_data/seabirds_cleaned.csv"))
```


Bird with the most individual sightings


```{r}
# Make a table of common, scientific and abbreviated species names
seabirds_species <- seabirds_full_clean %>% 
  select(species_scientific_name,
         species_abbreviation,
         species_common_name) %>%
  distinct()
```


```{r}
seabirds_full_clean %>%
  group_by(species_abbreviation) %>%
  summarise(sightings_count = n()) %>%
  slice_max(sightings_count, n=1) %>%
  left_join(seabirds_species, by = "species_abbreviation")
```

Bird with the highest total count

```{r}
seabirds_full_clean %>%
  group_by(species_abbreviation) %>%
  summarise(sightings_count = n(),
            total_count = sum(count)) %>%
  slice_max(total_count, n=1) %>%
  left_join(seabirds_species, by = "species_abbreviation")

```

Bird with the highest total count above latitude -30
```{r}
seabirds_full_clean %>%
  filter(lat > -30) %>%
  group_by(species_abbreviation) %>%
  summarise(sightings_count = n(),
            total_count = sum(count)) %>%
  slice_max(total_count, n=1) %>%
  left_join(seabirds_species, by = "species_abbreviation")
```

How many different types of birds only ever seen in groups of 1

```{r}
#table of birds sighted once
seabirds_single_sightings <- seabirds_full_clean %>%
  filter(count == 1) %>%
  group_by(species_abbreviation) %>%
  summarise(sightings = n())

#table of birds sighted in groups
seabirds_group_sightings <- seabirds_full_clean %>%
  filter(count > 1) %>%
  group_by(species_abbreviation) %>%
  summarise(sightings = n())

#perform anti-join to find birds who were not sighted in a group
anti_join(seabirds_single_sightings,
          seabirds_group_sightings,
          by = "species_abbreviation") %>%
  nrow()
```

